
# Introduction to pandas and Jupyter

This code is from the following notebooks (combined): https://ethanweed.github.io/pythonbook/landingpage.html 
https://github.com/jakevdp/PythonDataScienceHandbook/blob/master/notebooks_v1/03.01-Introducing-Pandas-Objects.ipynb

In [9]:
import pandas
pandas.__version__

'2.3.3'

If not installed, you need to run the following cell:

In [10]:
pip install pandas

Requirement already satisfied: pandas in /Users/madams1/Documents/FAU/boilerplate/.venv/lib/python3.9/site-packages (2.3.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/madams1/Documents/FAU/boilerplate/.venv/lib/python3.9/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: numpy>=1.22.4 in /Users/madams1/Documents/FAU/boilerplate/.venv/lib/python3.9/site-packages (from pandas) (1.26.4)
Requirement already satisfied: tzdata>=2022.7 in /Users/madams1/Documents/FAU/boilerplate/.venv/lib/python3.9/site-packages (from pandas) (2025.3)
Requirement already satisfied: pytz>=2020.1 in /Users/madams1/Documents/FAU/boilerplate/.venv/lib/python3.9/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /Users/madams1/Documents/FAU/boilerplate/.venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
WARNING: You are using pip version 21.2.4; however, version 26.0.1 is available.
You should consider upgrading via the '/Users/madams1/Documents/FAU/boilerplate/.venv/bin/python -m pip install --upgrade pip' command.
Note: you may need to restart the kernel to use updated packages.

Here is pandas documentation: https://pandas.pydata.org/getting_started.html

In [7]:
import pandas as pd

# Introducing Pandas Objects

Pandas provides a host of useful tools, methods, and functionality on top of the basic data structures, but nearly everything that follows will require an understanding of what these structures are.
Thus, before we go any further, let's introduce these three fundamental Pandas data structures: the ``Series``, ``DataFrame``, and ``Index``.

## The Pandas Series Object

A Pandas ``Series`` is a one-dimensional array of indexed data.
It can be created from a list or array as follows:

In [8]:
data = pd.Series([0.25, 0.5, 0.75, 1.0])
data

0    0.25
1    0.50
2    0.75
3    1.00
dtype: float64

As we see in the output, the ``Series`` wraps both a sequence of values and a sequence of indices, which we can access with the ``values`` and ``index`` attributes.
The ``values`` are simply a familiar NumPy array:

In [11]:
data.values

array([0.25, 0.5 , 0.75, 1.  ])

The ``index`` is an array-like object of type ``pd.Index``, which we'll discuss in more detail momentarily.

In [12]:
data.index

RangeIndex(start=0, stop=4, step=1)

Like with a NumPy array, data can be accessed by the associated index via the familiar Python square-bracket notation:

In [13]:
data[1]

0.5

In [18]:
data[1:3]

1    0.50
2    0.75
dtype: float64

From what we've seen so far, it may look like the ``Series`` object is basically interchangeable with a one-dimensional NumPy array.
The essential difference is the presence of the index: while the Numpy Array has an *implicitly defined* integer index used to access the values, the Pandas ``Series`` has an *explicitly defined* index associated with the values.

This explicit index definition gives the ``Series`` object additional capabilities. For example, the index need not be an integer, but can consist of values of any desired type.
For example, if we wish, we can use strings as an index:

In [21]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [22]:
data['b']

0.5

We can even do this

In [23]:
data = pd.Series([0.25, 0.5, 0.75, 1.0],
                 index=[2, 5, 3, 7])
data

2    0.25
5    0.50
3    0.75
7    1.00
dtype: float64

In [24]:
data[5]

0.5

### Series as specialized dictionary

In this way, you can think of a Pandas ``Series`` a bit like a specialization of a Python dictionary.
A dictionary is a structure that maps arbitrary keys to a set of arbitrary values, and a ``Series`` is a structure which maps typed keys to a set of typed values.
This typing is important: just as the type-specific compiled code behind a NumPy array makes it more efficient than a Python list for certain operations, the type information of a Pandas ``Series`` makes it much more efficient than Python dictionaries for certain operations.

The ``Series``-as-dictionary analogy can be made even more clear by constructing a ``Series`` object directly from a Python dictionary:

In [25]:
population_dict = {'California': 38332521,
                   'Texas': 26448193,
                   'New York': 19651127,
                   'Florida': 19552860,
                   'Illinois': 12882135}
population = pd.Series(population_dict)
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

How would you access the populaiton of California?

In [29]:
population['California']
print('California population:', population['California'])

California population: 38332521

Unlike a dictionary, though, the ``Series`` also supports array-style operations such as slicing:

In [27]:
population['California':'New York']

California    38332521
Texas         26448193
New York      19651127
dtype: int64

### Constructing Series objects

We've already seen a few ways of constructing a Pandas ``Series`` from scratch; all of them are some version of the following:

```python
>>> pd.Series(data, index=index)
```

where ``index`` is an optional argument, and ``data`` can be one of many entities.

For example, ``data`` can be a list or NumPy array, in which case ``index`` defaults to an integer sequence:

In [30]:
pd.Series([2, 4, 6])

0    2
1    4
2    6
dtype: int64

``data`` can be a scalar, which is repeated to fill the specified index:

In [31]:
pd.Series(5, index=[100, 200, 300])

100    5
200    5
300    5
dtype: int64

``data`` can be a dictionary, in which ``index`` defaults to the sorted dictionary keys:

In [32]:
pd.Series({2:'a', 1:'b', 3:'c'})

2    a
1    b
3    c
dtype: object

In each case, the index can be explicitly set if a different result is preferred:

In [33]:
pd.Series({2:'a', 1:'b', 3:'c'}, index=[3, 2])

3    c
2    a
dtype: object

Notice that in this case, the ``Series`` is populated only with the explicitly identified keys.


## The Pandas DataFrame Object


The next fundamental structure in Pandas is the ``DataFrame``.
Like the ``Series`` object discussed in the previous section, the ``DataFrame`` can be thought of either as a generalization of a NumPy array, or as a specialization of a Python dictionary.
We'll now take a look at each of these perspectives.

Dataframes - "a 2-dimensional data structure, or a table with rows and columns".

Just as you might think of a two-dimensional array as an ordered sequence of aligned one-dimensional columns, you can think of a ``DataFrame`` as a sequence of aligned ``Series`` objects.
Here, by "aligned" we mean that they share the same index.

To demonstrate this, let's first construct a new ``Series`` listing the area of each of the five states discussed in the previous section:

In [34]:
area_dict = {'California': 423967, 'Texas': 695662, 'New York': 141297,
             'Florida': 170312, 'Illinois': 149995}
area = pd.Series(area_dict)
area

California    423967
Texas         695662
New York      141297
Florida       170312
Illinois      149995
dtype: int64

Now that we have this along with the ``population`` Series from before, we can use a dictionary to construct a single two-dimensional object containing this information:

In [35]:
population

California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135
dtype: int64

In [36]:
states = pd.DataFrame({'population': population,
                       'area': area})
states

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

Like the ``Series`` object, the ``DataFrame`` has an ``index`` attribute that gives access to the index labels:

In [37]:
states.index

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')

Additionally, the ``DataFrame`` has a ``columns`` attribute, which is an ``Index`` object holding the column labels:

In [38]:
states.columns

Index(['population', 'area'], dtype='object')

### Constructing DataFrame objects

A Pandas ``DataFrame`` can be constructed in a variety of ways.
Here we'll give several examples.

#### From a single Series object

A ``DataFrame`` is a collection of ``Series`` objects, and a single-column ``DataFrame`` can be constructed from a single ``Series``:

In [41]:
pd.DataFrame(population, columns=['population'])

            population
California    38332521
Texas         26448193
New York      19651127
Florida       19552860
Illinois      12882135

#### From a dictionary of Series objects

As we saw before, a ``DataFrame`` can be constructed from a dictionary of ``Series`` objects as well:

In [42]:
pd.DataFrame({'population': population,
              'area': area})

            population    area
California    38332521  423967
Texas         26448193  695662
New York      19651127  141297
Florida       19552860  170312
Illinois      12882135  149995

#### From Python lists

In [45]:
age = [17, 19, 21, 37, 18, 19, 47, 18, 19]
score = [12, 10, 11, 15, 16, 14, 25, 21, 29]
rt = [3.552, 1.624, 6.431, 7.132, 2.925, 4.662, 3.634, 3.635, 5.234]
group = ["test", "test", "test", "test", "test", "control", "control", "control", "control"]

In [46]:
import pandas as pd

df = pd.DataFrame(
    {'age': age,
     'score': score,
     'rt': rt,
     'group': group
    })

Note. The lengths of data must be the same otherwise it'll throw an error!

In [52]:
df

   age  score     rt    group
0   17     12  3.552     test
1   19     10  1.624     test
2   21     11  6.431     test
3   37     15  7.132     test
4   18     16  2.925     test
5   19     14  4.662  control
6   47     25  3.634  control
7   18     21  3.635  control
8   19     29  5.234  control

### Pulling out the Series of a data frame

 To access the data in the `score` column by the column name, we can write:

In [53]:
score_data = df['score']
score_data

0    12
1    10
2    11
3    15
4    16
5    14
6    25
7    21
8    29
Name: score, dtype: int64

In [49]:
df.score # this is the same thing

0    12
1    10
2    11
3    15
4    16
5    14
6    25
7    21
8    29
Name: score, dtype: int64

We could also choose to ask for only data from e.g. the first 4 particpants. To do this, we write:

In [50]:
score_data = df['score'][0:4]
score_data

0    12
1    10
2    11
3    15
Name: score, dtype: int64

What if we want to get data from a row instead? In this case, we will use the loc attribute of a pandas dataframe, and use a number instead of name (i.e., no quotation marks), like this:

In [57]:
score_data = df.loc[2]
score_data

age         21
score       11
rt       6.431
group     test
Name: 2, dtype: object

If you look at the contents of score_data above, you will see that it is still not just the data: it also has information about the data, including which column and row it came from. And if we use type() to check, we can see that it is a pandas.core.series.Series.

In [54]:
type(score_data)

pandas.core.series.Series

The simplest way is to just turn it into a list variable, using the command `list()`:

In [55]:
my_row = list(score_data)
my_row

[12, 10, 11, 15, 16, 14, 25, 21, 29]

### Some more dataframe tips for the road

To get a list of the column names, you can use the command:

In [59]:
list(df)

['age', 'score', 'rt', 'group']

We can easily check to see how many rows and columns our dataframe has using `.shape`

In [60]:
df.shape

(9, 4)

The first number gives us the number of rows, and the second number is the number of columns. Our dataframe `df` is 9 rows long, and 4 columns wide.

 The dataframe attribute head() shows the first 5 lines of the dataframe:

In [62]:
df.head(6)

   age  score     rt    group
0   17     12  3.552     test
1   19     10  1.624     test
2   21     11  6.431     test
3   37     15  7.132     test
4   18     16  2.925     test
5   19     14  4.662  control

And if you want to see the last rows of the dataframe? `tail()` has got you covered:

In [63]:
df.tail()

   age  score     rt    group
4   18     16  2.925     test
5   19     14  4.662  control
6   47     25  3.634  control
7   18     21  3.635  control
8   19     29  5.234  control

Finally, if you just want to get all of your data out of the dataframe and into a list, then .values.tolist() will do the job, giving you a list of lists, with each item in the list containing the data for a single row:

In [64]:
df.values.tolist()

[[17, 12, 3.552, 'test'],
 [19, 10, 1.624, 'test'],
 [21, 11, 6.431, 'test'],
 [37, 15, 7.132, 'test'],
 [18, 16, 2.925, 'test'],
 [19, 14, 4.662, 'control'],
 [47, 25, 3.634, 'control'],
 [18, 21, 3.635, 'control'],
 [19, 29, 5.234, 'control']]

## Slicing and dicing your data

### Slicing a list:

"Slicing" is the most common way to get chunks of data out of a list.

In [65]:
age = [17, 19, 21, 37, 18, 19, 47, 18, 19]

Return the first four elements in the list:

In [66]:
age[0:4]

[17, 19, 21, 37]

Return the last four elements in the list

In [67]:
age[-4:]

[19, 47, 18, 19]

A different way to get the last four elements in the list:

In [68]:
age[5:len(age)]

[19, 47, 18, 19]

Return every second element, starting with the first

In [ ]:
age[::2]

Return every second element, starting with second

In [ ]:
age[1::2]

### "popping" items out of a list

Sometimes it is useful to remove an item from a list. In Python, lists have a property called `.pop()` that allow you to do just that. Nothing against spinach, but there is one item in the list of fruits below that isn't like the others. So let's `.pop` it out:

In [69]:
fruits = ['apples', 'pears', 'bananas', 'spinach', 'strawberries', 'grapes']
fruits.pop(3)
fruits

['apples', 'pears', 'bananas', 'strawberries', 'grapes']


## Extracting a subset of a dataframe

In [70]:
df

   age  score     rt    group
0   17     12  3.552     test
1   19     10  1.624     test
2   21     11  6.431     test
3   37     15  7.132     test
4   18     16  2.925     test
5   19     14  4.662  control
6   47     25  3.634  control
7   18     21  3.635  control
8   19     29  5.234  control

In [73]:
# select rows where the group is the test group
df_test = df[df['group'] == 'test']
df_test

   age  score     rt group
0   17     12  3.552  test
1   19     10  1.624  test
2   21     11  6.431  test
3   37     15  7.132  test
4   18     16  2.925  test

In [74]:
# select rows where observations belong to the control group

df_control = df[df['group'] == 'control']
df_control

   age  score     rt    group
5   19     14  4.662  control
6   47     25  3.634  control
7   18     21  3.635  control
8   19     29  5.234  control

In [75]:
# select rows where individuals are older than 21
df_old = df[df['age']> 21] 
df_old

   age  score     rt    group
3   37     15  7.132     test
6   47     25  3.634  control

In [77]:
# select rows where individuals are younger than 21 and older than 17

df_youngish = df[(df['age'] < 21 ) & (df['age'] > 17)]
df_youngish

   age  score     rt    group
1   19     10  1.624     test
4   18     16  2.925     test
5   19     14  4.662  control
7   18     21  3.635  control
8   19     29  5.234  control

In [78]:
old_and_slow = df[(df['age'] > 21) & (df['rt'] > 3)]
old_and_slow

   age  score     rt    group
3   37     15  7.132     test
6   47     25  3.634  control

In [79]:
old_and_slow_control = df[(df['age'] > 21) & (df['rt'] > 3) & (df['group'] == 'control')]
old_and_slow_control

   age  score     rt    group
6   47     25  3.634  control

## Sorting, flipping, and merging dataframes

### Sorting dataframes

In [ ]:
df

#### Sorting by a column

In [86]:
df_sorted = df.sort_values(by=['group'])
df_sorted

   age  score     rt    group
5   19     14  4.662  control
6   47     25  3.634  control
7   18     21  3.635  control
8   19     29  5.234  control
0   17     12  3.552     test
1   19     10  1.624     test
2   21     11  6.431     test
3   37     15  7.132     test
4   18     16  2.925     test

#### Sorting from largest to smallest

In [83]:
df_sorted = df.sort_values(by=['age'], ascending = False)
df_sorted

   age  score     rt    group
6   47     25  3.634  control
3   37     15  7.132     test
2   21     11  6.431     test
1   19     10  1.624     test
5   19     14  4.662  control
8   19     29  5.234  control
4   18     16  2.925     test
7   18     21  3.635  control
0   17     12  3.552     test

#### Sorting by multiple columns

In [84]:
df_sorted = df.sort_values(by=['age', 'score'])
df_sorted

   age  score     rt    group
0   17     12  3.552     test
4   18     16  2.925     test
7   18     21  3.635  control
1   19     10  1.624     test
5   19     14  4.662  control
8   19     29  5.234  control
2   21     11  6.431     test
3   37     15  7.132     test
6   47     25  3.634  control

### Flipping (transposing) a dataframe

In [87]:
import pandas as pd

df_cakes = pd.read_csv("https://raw.githubusercontent.com/ethanweed/pythonbook/main/Data/cakes.csv")
df_cakes

   time.1  time.2  time.3  time.4  time.5
0     100      80       0       0       0
1     100     100      90      30      10
2     100      20      20      20      20
3     100     100     100     100     100

In [88]:
df_cakes_flipped = df_cakes.transpose()
df_cakes_flipped

          0    1    2    3
time.1  100  100  100  100
time.2   80  100   20  100
time.3    0   90   20  100
time.4    0   30   20  100
time.5    0   10   20  100